on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: TaintImpact
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run TaintImpact
        uses: ./ # Uses an action in the root directory
        id: build_taint_impact
        with:
          who-to-greet: "sudo cmake \
            -DCMAKE_CXX_COMPILER=/opt/llvm/bin/clang++1"
          build-command: "sudo make"
